server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: service-feign
  zipkin:
    base-url: http://localhost:9411/

feign:
  hystrix:
    enabled: true