server:
  port: 8080
spring:
  application:
    name: service-web
  thymeleaf:
    prefix: classpath:/webapp # 默认是 classpath:/templates/
    suffix: .html # 默认是 .html
  mvc:
#    view:
#      prefix:  /
#      suffix:  .html
    static-path-pattern: /webapp/static/**
  resources:
    static-locations: classpath:/webapp/static/
