server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: true # 默认是 true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    registerWithEureka: false
    fetchRegistry: false