spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri:
          searchPaths: config
          username:
          password:

server:
  port: 8888